variables:
  ONLY: 
    value: ""
    description: "Only build some components: frontend or backend. Or both with space."


workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: always
    - if: $CI_COMMIT_BRANCH == 'main'
      when: always
    - if: $CI_COMMIT_TAG
      when: always
    - if: $ONLY != ''
      when: always
    - when: never

child:
  stage: build
  variables:
    COMPONENT: $COMPONENT
  trigger:
    include: "services/${COMPONENT}/.gitlab-ci.yml"
    strategy: depend
  rules:
    - if: $COMPONENT =~ $ONLY
      when: always
    - if: $CI_COMMIT_TAG
      when: always
    - if: $ONLY == ""
      changes:
        - services/$COMPONENT/**/*
  parallel:
    matrix:
    - COMPONENT: [ backend, frontend, keycloak, documentation ]
